### ISSUE TITLE
tskill not available on Windows Home editions

### ISSUE THREAD

**Issue by mcs** [mcs/robotmon-alive-monitor#2]
Although more reliable (at least in some of my past operational cases), `tskill` is not available on every Windows platform. Ideally, the program would check if `tskill` is installed and available, and use `taskkill` instead if not.

**Comment by angjunkang** [comment]
Completed with #3 with additional bug fixes for outbound ip address after testing it multiple times ._. (Sorry ><)

**Comment by mcs** [comment]
Resolved with #3
Thank you for the contribution 👍
